Traceback (most recent call last):
  File "C:\Python310\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Python310\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Python310\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Python310\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Python310\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
# try out the following example where we try adding 30 to the output of the function
# ... you should get an error!

#defining the function
def function_example4(a,b):
    print(a + b)
    
    
# calling the function & trying to add 30 to the output
function_example4(5,10) + 30   
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mTypeError[0m                                 Traceback (most recent call last)
Input [1;32mIn [6][0m, in [0;36m<cell line: 10>[1;34m()[0m
[0;32m      6[0m     [38;5;28mprint[39m(a [38;5;241m+[39m b)
[0;32m      9[0m [38;5;66;03m# calling the function & trying to add 30 to the output[39;00m
[1;32m---> 10[0m [43mfunction_example4[49m[43m([49m[38;5;241;43m5[39;49m[43m,[49m[38;5;241;43m10[39;49m[43m)[49m[43m [49m[38;5;241;43m+[39;49m[43m [49m[38;5;241;43m30[39;49m

[1;31mTypeError[0m: unsupported operand type(s) for +: 'NoneType' and 'int'
TypeError: unsupported operand type(s) for +: 'NoneType' and 'int'

